// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 David Liptak
//
// One-shot: write tests/data/hcnw_interop/ for Python cross-language load tests.
// Build (after CMake knows this target) or compile against libHypercubeCNNCore.a.
//
// Usage: write_hcnw_interop_fixture [out_dir]
// Default out_dir: tests/data/hcnw_interop relative to cwd (repo root).

#include "HCNN.h"
#include "HCNNArch.h"
#include "HCNNTrainHelpers.h"

#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using namespace hcnn;

static void write_floats(const fs::path& path, const float* v, int n) {
    std::ofstream os(path);
    if (!os)
        throw std::runtime_error("cannot write " + path.string());
    os.precision(9);
    os << std::scientific;
    for (int i = 0; i < n; ++i) {
        if (i) os << ' ';
        os << v[i];
    }
    os << '\n';
}

int main(int argc, char** argv) {
    try {
        fs::path out = (argc > 1)
            ? fs::path(argv[1])
            : fs::path("tests/data/hcnw_interop");
        fs::create_directories(out);

        // Tiny fixed arch: dim=5, N=32, 2 classes, one conv (matches Python tests).
        HCNNConfig cfg;
        cfg.start_dim = 5;
        cfg.num_outputs = 2;
        cfg.input_channels = 1;
        cfg.task = TaskType::Classification;
        cfg.num_threads = 1;
        cfg.layers = {LayerSpec::Conv(4, Activation::RELU, /*bias=*/true, /*bn=*/false)};
        cfg.randomize = true;
        cfg.weight_scale = 0.0f;
        cfg.weight_seed = 7;
        cfg.optimizer = OptimizerType::ADAM;

        auto net = cfg.Build();
        if (!net)
            throw std::runtime_error("Build returned null");

        // Deterministic input
        const int N = net->GetStartN();
        std::vector<float> x(static_cast<size_t>(N), 0.0f);
        x[0] = 1.0f;
        x[3] = -0.5f;
        x[static_cast<size_t>(N) - 1] = 0.25f;

        std::vector<float> logits(static_cast<size_t>(net->GetNumOutputs()));
        net->Predict(x.data(), N, logits.data());

        // Arch JSON (Python hcnn_arch v1 — keep field names stable)
        {
            std::ofstream os(out / "model.arch.json");
            if (!os)
                throw std::runtime_error("cannot write arch json");
            os << "{\n"
               << "  \"format\": \"hcnn_arch\",\n"
               << "  \"version\": 1,\n"
               << "  \"dim\": 5,\n"
               << "  \"num_outputs\": 2,\n"
               << "  \"input_channels\": 1,\n"
               << "  \"task\": \"classification\",\n"
               << "  \"layers\": [\n"
               << "    {\"kind\": \"conv\", \"c_out\": 4, \"activation\": \"relu\", "
               << "\"use_bias\": true, \"use_bn\": false}\n"
               << "  ]\n"
               << "}\n";
        }

        save_weights(*net, (out / "model.hcnw").string());
        write_floats(out / "input.txt", x.data(), N);
        write_floats(out / "expected_logits.txt", logits.data(),
                     net->GetNumOutputs());

        // README for humans
        {
            std::ofstream os(out / "README.md");
            os << "# HCNW interop fixture (C++ → Python)\n\n"
               << "Generated by `tests/write_hcnw_interop_fixture.cpp`.\n\n"
               << "- **model.hcnw** — C++ `hcnn::save_weights`\n"
               << "- **model.arch.json** — Python-compatible arch sidecar\n"
               << "- **input.txt** / **expected_logits.txt** — full-capacity "
                  "input and C++ `Predict` logits\n\n"
               << "Python: rebuild from arch, `load_weights`, assert logits "
                  "match (bit-identical preferred).\n"
               << "Regenerate from repo root after building the tool:\n\n"
               << "```text\n"
               << "write_hcnw_interop_fixture tests/data/hcnw_interop\n"
               << "```\n";
        }

        std::cout << "Wrote HCNW interop fixture under " << out << "\n"
                  << "  weight_count=" << net->GetWeightCount()
                  << "  N=" << N
                  << "  logits=" << logits[0] << " " << logits[1] << "\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "write_hcnw_interop_fixture: " << e.what() << "\n";
        return 1;
    }
}
